# run using: $ ansible-playbook ./playbook.yml -K
---
- hosts: hosts
  remote_user: root
  tasks:
  - name: Install python dnf
    shell: dnf install -y python2-dnf
    become: yes
  - include: host-common.yml

