# run using: $ ansible-playbook ./playbook.yml -K
---
# - hosts: hosts
- hosts: f25
  remote_user: root
  tasks:
  - include: includes/common/install-python-dnf-module.yml
  - include: includes/common/all.yml
  - include: includes/common/main-host.yml
# $ cat /etc/sysconfig/network-scripts/ifcfg-ens3
# DEVICE=ens3
# BRIDGE=ovirtmgmt
# ONBOOT=yes
# MTU=1500
# NM_CONTROLLED=no
# IPV6INIT=no
# $ cat /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
# DEVICE=ovirtmgmt
# TYPE=Bridge
# DELAY=0
# STP=off
# ONBOOT=yes
# BOOTPROTO=dhcp
# MTU=1500
# DEFROUTE=yes
# NM_CONTROLLED=no
  - stat: path=/etc/sysconfig/network-scripts/ifcfg-ens3
    register: ifcfg_ens3_stat
  - name: Fail if original network configuration file is missing
    fail:
      msg: File /etc/sysconfig/network-scripts/ifcfg-ens3 is expected but missing
    when: not ifcfg_ens3_stat.stat.exists
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      state: absent
      regexp: '^(?!(#|((DEVICE|BRIDGE|ONBOOT|MTU|NM_CONTROLLED|IPV6INIT)=)))'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^DEVICE='
      line: 'DEVICE=ens3'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^BRIDGE='
      line: 'BRIDGE=ovirtmgmt'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^ONBOOT='
      line: 'ONBOOT=yes'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^MTU='
      line: 'MTU=1500'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^NM_CONTROLLED='
      line: 'NM_CONTROLLED=no'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ens3
      regexp: '^IPV6INIT='
      line: 'IPV6INIT=no'
  - name: create ifcfg-ovirt-mgmt
    file:
      path: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      state: touch
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      state: absent
      regexp: '^(?!(#|((DEVICE|TYPE|DELAY|ONBOOT|BOOTPROTO|MTU|DEFROUTE|NM_CONTROLLED)=)))'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^DEVICE='
      line: 'DEVICE=ovirtmgmt'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^TYPE='
      line: 'TYPE=Bridge'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^DELAY='
      line: 'DELAY=0'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^STP='
      line: 'STP=off'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^ONBOOT='
      line: 'ONBOOT=yes'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^BOOTPROTO='
      line: 'BOOTPROTO=dhcp'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^MTU='
      line: 'MTU=1500'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^DEFROUTE='
      line: 'DEFROUTE=yes'
  - lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
      regexp: '^DEFROUTE='
      line: 'NM_CONTROLLED=no'
  - name: disable network manager service
    systemd: enabled=no name=NetworkManager
  - name: enable network service
    systemd: enabled=yes name=network
  - name: stat of /etc/resolv.conf
    stat: path=/etc/resolv.conf
    register: resolv_conf_stat
  - when: resolv_conf_stat.stat.islnk
#    name: Fix of /etc/resolv.conf being a symlink to some network manager file
    block:
      - name: remove /etc/resolv.conf simlink
        file:
          path: /etc/resolv.conf
          state: absent
      - name: create empty /etc/resolv.conf
        file:
          path: /etc/resolv.conf
          state: touch
  - name: install vdsm
    dnf: name=vdsm state=present
