# run using: $ ansible-playbook -K ./main.yml
---
- hosts: localhost
  vars_files:
    - private-vars.yml
  tasks:
  - include: includes/common/install-python-dnf-module.yml
  - include: includes/common/all.yml
  - include: includes/common/main-host.yml
  - include: include/common/workstation.yml
  - dnf: name=libselinux-python state=present
    become: yes
  - name: install virt manager
    dnf: name=virt-manager state=present
    become: yes
# TODO move to workstation together with private-vars.yml import
  - git_config: name=user.name scope=global value={{ git.user_name }}
  - git_config: name=user.email scope=global value={{ git.user_email }}
  - name: install pgadmin3
    dnf: name=pgadmin3 state=present
    become: yes
  - name: install postgresql
    dnf: name=postgresql state=present
    become: yes
  - dnf: name=postgresql-server state=present
    become: yes
