# run using: $ ansible-playbook -K ./main.yml
---
- hosts: localhost
  vars_files:
    - private-vars.yml
    - vars.yml
  tasks:
  - include: includes/common/install-python-dnf-module.yml
  - include: includes/common/all.yml
  - include: includes/common/main-host.yml
  - include: include/common/workstation.yml
  - dnf: name=libselinux-python state=present
    become: yes
  - name: install virt manager
    dnf: name=virt-manager state=present
    become: yes
  - name: install pgadmin3
    dnf: name=pgadmin3 state=present
    become: yes
  - name: install postgresql
    dnf: name=postgresql state=present
    become: yes
  - dnf: name=postgresql-server state=present
    become: yes
  - dnf: name=virt-preview state=present
    become: yes

  # Bash aliases
  - name: kinit
    lineinfile:
      path: "{{ansible_user_dir}}/.bashrc"
      regexp: "^kinit="
      line: "kinit='kinit {{kinit.user_name}}'"
