---
- name: Create GOPATH directory
  file:
    path: '{{ ansible_user_dir}}/go'
    state: directory
- name: Set GOPATH environment variable
  lineinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    regexp: '^GOPATH='
    line: 'GOPATH={{ ansible_user_dir}}/go'
- name: Export GOPATH environment variable
  lineinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    regexp: '^\s*export GOPATH'
    line: 'export GOPATH'
- name: Add GOPATH/bin to PATH
  lineinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    insertafter: '^(export )?GOPATH'
    regexp: '^PATH=.*\$GOPATH/bin'
    line: 'PATH=$GOPATH/bin:$PATH'