---
- name: "does node.js dir exist?"
  stat:
    path: "{{ ansible_user_dir }}/opt/nodejs/latest"
  register: nodejs_dir_stat
#- block:
# download https://nodejs.org/dist/latest/SHASUMS256.txt, grep the file name, 
- name: "node.js in PATH"
  lineinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    regexp: '^\w*PATH=\W*\$HOME/opt/nodejs/latest/bin'
    line: 'PATH=$HOME/opt/nodejs/latest/bin:$PATH'
    insertbefore: '^\w*export PATH$'